# Generated by Django 3.1.5 on 2021-09-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_olish', models.CharField(blank=True, max_length=20, null=True)),
                ('euro_olish', models.CharField(blank=True, max_length=20, null=True)),
                ('euro_sotish', models.CharField(blank=True, max_length=20, null=True)),
                ('dollar_sotish', models.CharField(blank=True, max_length=20, null=True)),
                ('banklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.banklar')),
            ],
        ),
    ]
