# Generated by Django 3.1.5 on 2021-09-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='banklar',
            new_name='bank',
        ),
    ]
