# Generated by Django 3.1.5 on 2021-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210907_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='dollar_olish',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='dollar_sotish',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='euro_olish',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='euro_sotish',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
