# Generated by Django 3.1.5 on 2021-09-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210907_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='bank',
            new_name='banklar',
        ),
    ]
