# Generated by Django 3.1.5 on 2021-09-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210907_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='banklar',
            new_name='bank',
        ),
    ]
