# Generated by Django 3.1.5 on 2021-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210907_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
